name: "cnvkit antitarget"
description: >
 Given a “target” BED file that lists the chromosomal coordinates of the tiled regions used for targeted resequencing, derive 
 a BED file off-target/”antitarget” regions. See documentation https://cnvkit.readthedocs.io/en/stable/pipeline.html
input:
  - bed: bed file
  - accessible: sequence-accessible coordinates in chromosomes from the given reference genome
output:
  - bed: bed file
params:
  - extra: additional parameters that will be forwarded to cnvkit antitarget
authors:
  - Patrik Smeds
