name: "cnvkit scatter"
description: >
 Plot bin-level log2 coverages and segmentation calls together. Without any further arguments, this plots the genome-wide copy number in a form familiar to those who have used array CGH.
url: https://cnvkit.readthedocs.io/en/stable/plots.html?highlight=diagram#scatter
input:
  - cnr file
  - cns file
output:
  - plot
params:
  - extra: additional parameters that will be forwarded to cnvkit scatter
authors:
  - Patrik Smeds
